dist: xenial
language: python
python:
  - "3.7"
addons:
  postgresql: "11"
services:
  - redis-server
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - export DB_NAME=testing_db
install:
  - pip install -r requirements.txt
script:
  - flake8 service_api/
  - mypy service_api/ --ignore-missing-imports
  - py.test tests/