dist: xenial
language: python
python:
  - "3.7"
addons:
  postgresql: "11"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - export DB_NAME=testing_db
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE {{your database name here}};' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
services:
  - redis-server
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - flake8 service_api/
  - mypy service_api/ --ignore-missing-imports
  - py.test tests/